# Generated by Django 4.2.7 on 2023-11-22 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_work', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('client_name', models.CharField(max_length=256)),
                ('client_phone_number', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('date_ready', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_in_orders', to='workshop.order')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_in_orders', to='workshop.part')),
            ],
        ),
        migrations.CreateModel(
            name='PartsOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_in_orders', to='workshop.order')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_in_orders', to='workshop.part')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='parts',
            field=models.ManyToManyField(to='workshop.part'),
        ),
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Работник принявший заказ'),
        ),
        migrations.CreateModel(
            name='CustomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_services_in_orders', to='workshop.order')),
            ],
        ),
    ]
